In [1]:
import numpy as np

a = np.zeros(10)
print(a)

b = np.full((2,10), 0.7)
print(b)

c = np.linspace(0,25,7)
print(c)

print(type(c))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7]
 [0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7]]
[ 0.          4.16666667  8.33333333 12.5        16.66666667 20.83333333
 25.        ]
<class 'numpy.ndarray'>


In [38]:
def read_file(file_name):
    """ Reads in a file.

    [IMPLEMENT ME]
        1. Open and read the given file into a variable using the File read()
           function
        2. Print the contents of the file
        3. Return the contents of the file

    Args:
        file_name: the name of the file to be read

    Returns:
        string: contents of the given file.
    """
    ### WRITE SOLUTION HERE
    file = open(file_name, "r")
    data = file.read()

    print(data)
    return data
    file.close()
    
    raise NotImplementedError()

def read_file_into_list(file_name):
    """ Reads in a file and stores each line as an element in a list

    [IMPLEMENT ME]
        1. Open the given file
        2. Read the file line by line and append each line to a list
        3. Return the list

    Args:
        file_name: the name of the file to be read

    Returns:
        list: a list where each element is a line in the file.
    """
    ### WRITE SOLUTION HERE
    list = [ ]
    with open(file_name, "r") as file:
        for eachline in file.readlines():
            list.append(eachline)
    
    return list
    raise NotImplementedError()

def write_first_line_to_file(file_contents, output_filename):
    """ Writes the first line of a string to a file.

    [IMPLEMENT ME]
        1. Get the first line of file_contents
        2. Use the File write() function to write the first line into a file
           with the name from output_filename

        We determine the first line to be everything in a string before the
        first newline ('\n') character.

    Args:
        file_contents: string to be split and written into output file
        output_filename: the name of the file to be written to
    """
    ### WRITE SOLUTION HERE
    str = ""
    for eachline in file_contents:
        if (eachline == '\n'):
            break
        str += eachline

    with open(output_filename, 'w') as file:
        new_line = file.write(str)

    #raise NotImplementedError()


def read_even_numbered_lines(file_name):
    """ Reads in the even numbered lines of a file

    [IMPLEMENT ME]
        1. Open and read the given file into a variable
        2. Read the file line-by-line and add the even-numbered lines to a list
        3. Return the list

    Args:
        file_name: the name of the file to be read

    Returns:
        list: a list of the even-numbered lines of the file
    """
    ### WRITE SOLUTION HERE
    list = [ ]
    i = 1
    with open(file_name, "r") as file:
        for line in file.readlines():
            if i % 2 == 0:
                list.append(line)
            i += 1
    return list

    raise NotImplementedError()

def read_file_in_reverse(file_name):
    """ Reads a file and returns a list of the lines in reverse order

    [IMPLEMENT ME]
        1. Open and read the given file into a variable
        2. Read the file line-by-line and store the lines in a list in reverse order
        3. Print the list
        4. Return the list

    Args:
        file_name: the name of the file to be read

    Returns:
        list: list of the lines of the file in reverse order.
    """
    ### WRITE SOLUTION HERE
    list = []
    file = open(file_name, "r")
    lines = file.readlines()
    for line in reversed(lines):
        list.append(line)
    return list
    file.close()
    raise NotImplementedError()

'''
Here are some sample commands to help you run/test your implementations.
Feel free to uncomment/modify/add to them as you wish.
'''
def main():


    file_contents = read_file("sampletext.txt")
    #print(read_file_into_list("sampletext.txt"))
    write_first_line_to_file(file_contents, "online.txt")
    #print(read_even_numbered_lines("sampletext.txt"))
    #print(read_file_in_reverse("sampletext.txt"))


In [39]:
# Input data: List of dictionaries
employee_list = [
   {"id": 12345, "name": "John", "department": "Kitchen"},
   {"id": 12456, "name": "Paul", "department": "House Floor"},
   {"id": 12478, "name": "Sarah", "department": "Management"},
   {"id": 12434, "name": "Lisa", "department": "Cold Storage"},
   {"id": 12483, "name": "Ryan", "department": "Inventory Mgmt"},
   {"id": 12419, "name": "Gill", "department": "Cashier"}
]

# Function to be passed to the map() function. Do not change this.
def mod(employee_list):
   temp = employee_list['name'] + "_" + employee_list["department"]
   return temp

def to_mod_list(employee_list):
   """ Modifies the employee list of dictionaries into list of employee-department strings

   [IMPLEMENT ME] 
      1. Use the map() method to apply mod() to all elements in employee_list

   Args:
      employee_list: list of employee objects

   Returns:
      list - A list of strings consisting of name + department.
   """
   ### WRITE SOLUTION CODE HERE
   li = list(map(mod,employee_list))
  
   return li
   raise NotImplementedError()

def generate_usernames(mod_list):

   """ Generates a list of usernames 

   [IMPLEMENT ME] 
      1. Use list comprehension and the replace() function to replace space
         characters with underscores

      List comprehension looks like:
      list = [ function() for <item> in <list> ]

      The format for the replace() function is:

      test_str.replace(“a”, “z”) # replaces every “a” in test_str with “z”

   Args:
      mod_list: list of employee-department strings

   Returns:
      list - A list of usernames consisting of name + department delimited by underscores.
   """
   ### WRITE SOLUTION CODE HERE
   li = []
   for i in mod_list:
      li.append(i.replace(" ","_"))
      
   return li
   raise NotImplementedError()

def map_id_to_initial(employee_list):
   """ Maps employee id to first initial

   [IMPLEMENT ME] 
      1. Use dictionary comprehension to map each employee's id (value) to the first letter in their name (key)

      Dictionary comprehension looks like:
      dict = { key : value for <item> in <list> }

   Args:
      employee_list: list of employee objects

   Returns:
      dict - A dictionary mapping an employee's id (value) to their first initial (key).
   """
   ### WRITE SOLUTION CODE HERE
   # d = dict()
   d = {i['name'][0]:i['id'] for i in employee_list}
   # for i in employee_list:
   #    d[i['id']] = i['name'][0]
   return d
   raise NotImplementedError()

def main():
   mod_emp_list = to_mod_list(employee_list)
   print("Modified employee list: " + str(mod_emp_list) + "\n")

   print(f"List of usernames: {generate_usernames(mod_emp_list)}\n")
   # map_id_to_initial(employee_list)
   print(f"Initials and ids: {map_id_to_initial(employee_list)}")


In [40]:
import numpy as np

a = np.zeros(10)
print(a)

b = np.full((2,10), 0.7)
print(b)

c = np.linspace(0,25,7)
print(c)

print(type(c))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7]
 [0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7]]
[ 0.          4.16666667  8.33333333 12.5        16.66666667 20.83333333
 25.        ]
<class 'numpy.ndarray'>


In [2]:
import pandas as pd

a = pd.DataFrame({'Animals': ['Dog','Cat','Lion','Cow','Elephant'],
                    'Sounds':['Barks','Meow','Roars','Moo','Trumpet']})

print(a)
print(a.describe())

b = pd.DataFrame({
    "Letters" : ['a', 'b', 'c', 'd', 'e', 'f'],
    "Numbers" : [12, 7, 9, 3, 5, 1]  })

print(b.sort_values(by="Numbers"))

b = b.assign(new_values = b['Numbers']*3)
print(b)



    Animals   Sounds
0       Dog    Barks
1       Cat     Meow
2      Lion    Roars
3       Cow      Moo
4  Elephant  Trumpet
       Animals Sounds
count        5      5
unique       5      5
top        Dog  Barks
freq         1      1
  Letters  Numbers
5       f        1
3       d        3
4       e        5
1       b        7
2       c        9
0       a       12
  Letters  Numbers  new_values
0       a       12          36
1       b        7          21
2       c        9          27
3       d        3           9
4       e        5          15
5       f        1           3


In [41]:
# Import ABC and abstractmethod from the module abc (which stands for abstract base classes)
from abc import ABC, abstractmethod

# Class Bank
class Bank(ABC):
    """ An abstract bank class

    [IMPLEMENT ME]
        1. This class must derive from class ABC
        2. Write a basicinfo() function that prints out "This is a generic bank" and
           returns the string "Generic bank: 0" 
        3. Define a second function called withdraw and keep it empty by
           adding the `pass` keyword under it. Make this function abstract by
           adding an '@abstractmethod' tag right above the function declaration.
    """
    ### YOUR CODE HERE
    def basicinfo(self):
        print('This is a generic bank')
        return 'Generic bank: 0'
    
    @abstractmethod
    def withdraw():
        pass

# Class Swiss
class Swiss(Bank):
    """ A specific type of bank than derives from class Bank

    [IMPLEMENT ME]
        1. This class must derive from class Bank
        2. Create a constructor for this class that initializes a class
           variable `bal` to 1000
        3. Implement the basicinfo() function so that it prints "This is the 
           Swiss Bank" and returns a string with "Swiss Bank: " (don't forget
           the space after the colon) followed by the current bank balance.

           For example, if self.bal = 80, then it would return "Swiss Bank: 80"

        4. Implement withdraw so that it takes one argument (in addition to
           self) that is an integer which represents the amount to be withdrawn
           from the bank. Deduct the withdrawn amount from the bank bal, print 
           the withdrawn amount ("Withdrawn amount: {amount}"), print the new
           balance ("New Balance: {self.bal}"), and return the new balance.

           Note: Make sure to verify that there is enough money to withdraw!  
                 If amount is greater than balance, then do not deduct any 
                 money from the class variable `bal`. Instead, print a 
                 statement saying `"Insufficient funds"`, and return the 
                 original account balance instead.
    """
    ### YOUR CODE HERE
    def __init__(self):
        self.bal = 1000


    def basicinfo(self):
        print("This is the Swiss Bank")
        return "Swiss Bank: " + str(self.bal)
    def withdraw(self,amount):
        if amount>self.bal:
            print("Insufficient funds")
            return self.bal
        self.bal = self.bal - amount
        
        print("Withdrawn amount: {}".format(amount))
        print("New Balance: {}".format(self.bal))
        return self.bal
# Driver Code
def main():
    assert issubclass(Bank, ABC), "Bank must derive from class ABC"
    s = Swiss()
    print(s.basicinfo())
    s.withdraw(30)
    s.withdraw(1000)


In [21]:
"""
import nltk
from tokenize import tokenize
#import word_tokenize
from nltk.corpus import stopwords

text = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
# Print statement 1
print(tokenize(text))
# Print statement 2
print(nltk.tokenize.sent_tokenize(text))


stopwords = stopwords.words("english")
new_text = []
for i in text.split():
    if i not in stopwords:
        new_text.append(i)

# Print statement 3
print(new_text)
"""


'\nimport nltk\nfrom tokenize import tokenize\n#import word_tokenize\nfrom nltk.corpus import stopwords\n\ntext = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."\n# Print statement 1\nprint(tokenize(text))\n# Print statement 2\nprint(nltk.tokenize.sent_tokenize(text))\n\n\nstopwords = stopwords.words("english")\nnew_text = []\nfor i in text.split():\n    if i not in stopwords:\n        new_text.append(i)\n\n# Print statement 3\nprint(new_text)\n'

In [4]:
"""
Big Data and Analysis with Python

RedShift and S3: Amazon services are used with their cloud services. S3 is a storage service and RedShift is a data warehousing service.

BigQuery: Developed by Google, BigQuery is a Cloud service library that is useful with RESTful APIs.

PySpark: This is an open-source framework used for large scale data processing and works with resilient distributed datasets.

Kafka: This is a publish-subscribe messaging system that receives logs in the form of packages and is stored in partitioned spaces.

Pydoop: Pydoop provides an interface between Hadoop and Python and support for handling its Hadoop distributed file systems.
"""

'\nBig Data and Analysis with Python\n\nRedShift and S3: Amazon services are used with their cloud services. S3 is a storage service and RedShift is a data warehousing service.\n\nBigQuery: Developed by Google, BigQuery is a Cloud service library that is useful with RESTful APIs.\n\nPySpark: This is an open-source framework used for large scale data processing and works with resilient distributed datasets.\n\nKafka: This is a publish-subscribe messaging system that receives logs in the form of packages and is stored in partitioned spaces.\n\nPydoop: Pydoop provides an interface between Hadoop and Python and support for handling its Hadoop distributed file systems.\n'

In [5]:
# https://towardsdatascience.com/best-python-libraries-for-machine-learning-and-deep-learning-b0bd40c7e8c

In [23]:
#Testing using pytest
# Given implementations of some string-related methods. 
# DO NOT CHANGE THIS FILE

def word_count(sentence):
    # Function to check the number of words. Returns the word count in string.
    words = len(sentence.split())
    print(words)
    return words

def char_count(sentence):
    # Function to check the number of characters. Returns the character count in string.
    chars = len(sentence)
    print(chars)
    return chars

def first_char(sentence):
    # Function to check the first character using the string index. Returns the first character in string.
    first = sentence[0]
    return first

def last_char(sentence):
    # Function to check the last character using the string index. Returns the last character in string.
    last = sentence[-1]
    return last
''' 
Import statements: 
    1. Import pytest and spellcheck modules
'''

' \nImport statements: \n    1. Import pytest and spellcheck modules\n'

In [26]:

import pytest
#import spellcheck

### WRITE IMPORT STATEMENTS HERE

# String variables to be tested
alpha = "Checking the length & structure of the sentence."
beta = "This sentence should fail the test"

# Do not delete this function. You may change the value assigned to input to test different inputs to your test functions.
@pytest.fixture
def input_value():
    input = alpha
    return input

# First test function test_length()
def test_length(input_value):
    """ Tests whether a string has fewer than 10 words and fewer than 50 chars.

    [IMPLEMENT ME]
        1. Use an assert statement to check the given string has fewer than 10 words
        2. Use an assert statement to check the given string has fewer than 50 chars

    Args:
      input_value: a function that returns a string, which can be configured
                   in the input_value() function
    """
    ### WRITE SOLUTION CODE HERE
    assert (spellcheck.word_count(input_value) < 10)
    assert (spellcheck.char_count(input_value) < 50)
 #   raise NotImplementedError()

# Second test function test_struc()
def test_struc(input_value):
    """ Tests whether a string begins with a capital letter and ends with a period.

    [IMPLEMENT ME]
        1. Use an assert statement to check the given string begins with a capital letter
        2. Use an assert statement to check the given string end with a period ('.')

    Args:
      input_value: a function that returns a string, which can be configured
                   in the input_value() function
    """
    ### WRITE SOLUTION CODE HERE
    assert (spellcheck.first_char(input_value).isupper())
    assert (spellcheck.last_char(input_value) == '.')
 #   raise NotImplementedError()

# Run these tests with `python3 -m pytest test_spellcheck.py`

In [27]:
names = ["Anna", "Natasha", "Mike"]
names.insert(2, "Xi")
print(names)

['Anna', 'Natasha', 'Xi', 'Mike']


In [29]:
sample_dict = {1: 'Coffee', 2: 'Tea', 3: 'Juice'}
for x in sample_dict:
    print(x)

1
2
3


In [30]:
def recursion(num):
    print(num)
    next = num - 3
    if next > 1:
        recursion(next)

recursion(11)

11
8
5
2


In [33]:
def d():
    color = "green"
    def e():
        nonlocal color
        color = "yellow"
    e()
    print("Color: " + color)
    color = "red"
color = "blue"
d()

Color: yellow


In [34]:
num = 9
class Car:
    num = 5
    bathrooms = 2

def cost_evaluation(num):
    num = 10
    return num

class Bike():
    num = 11

cost_evaluation(num)
car = Car()
bike = Bike()
car.num = 7
Car.num = 2
print(num)

9


In [35]:
class A:
   def a(self):
       return "Function inside A"

class B:
   def a(self):
       return "Function inside B"

class C:
   pass

class D(C, A, B):
   pass

d = D()
print(d.a())

Function inside A


In [42]:
print("hi")

def say_hello():
    print("Hello there!")

print(say_hello())

camelCase = "rubaEgbaria"
snake_case = "ruba_egbaria"

# type casting 

x = 88.21
print(int(x)) # str(),float(),..

# Modify the line below
age = int(input('What is your age? '))
print(f"Type of age variable is: {type(age)}. It should be <class 'int'>")

# inputs 

val = input(" the value is : ")
print(val)

# conditions
# and contol flow
#Starter Code
favorites = ['Creme Brulee', 'Apple Pie', 'Churros', 'Tiramisú', 'Chocolate Cake']

for dessert in favorites:
    if dessert == 'Churros':
        pass
    print('Other desserts I like are', dessert) 

###################

num_list = [33,42,5,66,77,22,16,79,36,62,78,43,88,39,53,67,89,11]

count = 0

for x,num in enumerate(num_list):
    count += 1
    if num == 36:
        print('Number found at ', x)
        break

print(count)
input()

# how to convert to binary from decimal ?


hi
Hello there!
None
88


<class 'TypeError'>: int() argument must be a string, a bytes-like object or a real number, not 'Future'

What is your age?  32


In [44]:
# list : 

list1 = [ 1 , 2 , 3 , 5 ]
list2 = [ ' A ' , ' B ' , ' C ' ]
list3 = [ ' Hello ' , 1 , True , 40.22 ]
list4 = [ 1 , [ 2,3,4 ] , 5 , 6 ]

list1.insert ( len ( list1 ) , 6 )
print ( list1 , sep = " " )

#or 

list1.append(7)
print ( list1 , sep = " " )

# to add more values at once 
list1.extend ( [  8 , 9, 10 ] )
print ( list1 , sep = " " )

# remove 
list1.pop(2) # index 2 
del list1[2] # index 2
print ( list1 , sep = " " )

# 2. tuples 

my_tuple = (1 , ' strings ' , 4.5 , True, False)
print ( my_tuple.count ( ' strings ' ) )
print ( my_tuple.index(False))
 
 # anything declared in a tuple is immutable ( cant be changed )


 # sets 
set_a = { 1 , 2 , 3 ,4 ,5 } 
set_a.add ( 6 )
set_a.discard(3) # value not index 
set_a.remove(2) # value not index 
print ( set_a )

set_b = { 4 , 5 , 6 , 7 , 8 }
print ( set_a.union ( set_b ) ) # = print ( set_a | set_b )

print ( set_a.intersection ( set_b ) ) # = print ( set_a & set_b )

print ( set_a.difference(set_b )) # = print ( set_a - set_b )

print ( set_a.symmetric_difference ( set_b ) ) # = print ( set_a ^ set_b )

# the set is not a sequence, 

# dictionary 
sample_dict = { 1 : ' Coffee ' , 2 : ' Tea ' , 3 : ' Juice ' }
sample_dict [ 2 ] = 'mint tea '
del sample_dict [ 3 ]
print(sample_dict)


# args 
def sum_of ( * args ) :
   sum = 0
   for x in args :
       sum += x
   return sum
print ( sum_of ( 4 , 5 , 6 , 4 , 5 , 6 ) )

# kwargs 
def sum_of ( ** kwargs ):
    sum = 0
    for k , v in kwargs.items ( ) :
        sum += v
    return round ( sum , 2 )
#print ( sum_of ( coffee - 2.99 , cake - 4.55 , juice = 2.99 ) )

# with args, you could pass in any amount of non-keyword variables.
# With the kwargs, you can pass in any amount of keyword arguments.

#examples
employee_list = [{"id": 12345, "name": "John", "department": "Kitchen"}, {"id": 12458, "name": "Paul", "department": "House Floor"}]

def get_employee(id): 
    for employee in employee_list:
        if employee['id'] == id:
            return employee

print(get_employee(12458));
## OUTPUT
{'id': 12458, 'name': 'Paul', 'department': 'House Floor'}

# 2 
employee_dict = {
    12345: {
        "id": "12345",
        "name": "John", 
        "department": "Kitchen"    
    },
    12458: {
        "id": "12458",
        "name": "Paul", 
        "department": "House Floor"    
    }
}

def get_employee_from_dict(id):
    return employee_dict[id];


print(get_employee_from_dict(12458));
## OUTPUT
{'id': 12458, 'name': 'Paul', 'department': 'House Floor'}


[1, 2, 3, 5, 6]
[1, 2, 3, 5, 6, 7]
[1, 2, 3, 5, 6, 7, 8, 9, 10]
[1, 2, 6, 7, 8, 9, 10]
1
4
{1, 4, 5, 6}
{1, 4, 5, 6, 7, 8}
{4, 5, 6}
{1}
{1, 7, 8}
{1: ' Coffee ', 2: 'mint tea '}
30
{'id': 12458, 'name': 'Paul', 'department': 'House Floor'}
{'id': '12458', 'name': 'Paul', 'department': 'House Floor'}


{'id': 12458, 'name': 'Paul', 'department': 'House Floor'}

In [45]:
# files in python
def read_file(file_name):
    """ Reads in a file.

    [IMPLEMENT ME]
        1. Open and read the given file into a variable using the File read()
           function
        2. Print the contents of the file
        3. Return the contents of the file

    Args:
        file_name: the name of the file to be read

    Returns:
        string: contents of the given file.
    """
    ### WRITE SOLUTION HERE
    file = open(file_name, "r")
    data = file.read()

    print(data)
    return data
    file.close()
    
    raise NotImplementedError()

def read_file_into_list(file_name):
    """ Reads in a file and stores each line as an element in a list

    [IMPLEMENT ME]
        1. Open the given file
        2. Read the file line by line and append each line to a list
        3. Return the list

    Args:
        file_name: the name of the file to be read

    Returns:
        list: a list where each element is a line in the file.
    """
    ### WRITE SOLUTION HERE
    list = [ ]
    with open(file_name, "r") as file:
        for eachline in file.readlines():
            list.append(eachline)
    
    return list
    raise NotImplementedError()

def write_first_line_to_file(file_contents, output_filename):
    """ Writes the first line of a string to a file.

    [IMPLEMENT ME]
        1. Get the first line of file_contents
        2. Use the File write() function to write the first line into a file
           with the name from output_filename

        We determine the first line to be everything in a string before the
        first newline ('\n') character.

    Args:
        file_contents: string to be split and written into output file
        output_filename: the name of the file to be written to
    """
    ### WRITE SOLUTION HERE
    str = ""
    for eachline in file_contents:
        if (eachline == '\n'):
            break
        str += eachline

    with open(output_filename, 'w') as file:
        new_line = file.write(str)

    #raise NotImplementedError()


def read_even_numbered_lines(file_name):
    """ Reads in the even numbered lines of a file

    [IMPLEMENT ME]
        1. Open and read the given file into a variable
        2. Read the file line-by-line and add the even-numbered lines to a list
        3. Return the list

    Args:
        file_name: the name of the file to be read

    Returns:
        list: a list of the even-numbered lines of the file
    """
    ### WRITE SOLUTION HERE
    list = [ ]
    i = 1
    with open(file_name, "r") as file:
        for line in file.readlines():
            if i % 2 == 0:
                list.append(line)
            i += 1
    return list

    raise NotImplementedError()

def read_file_in_reverse(file_name):
    """ Reads a file and returns a list of the lines in reverse order

    [IMPLEMENT ME]
        1. Open and read the given file into a variable
        2. Read the file line-by-line and store the lines in a list in reverse order
        3. Print the list
        4. Return the list

    Args:
        file_name: the name of the file to be read

    Returns:
        list: list of the lines of the file in reverse order.
    """
    ### WRITE SOLUTION HERE
    list = []
    file = open(file_name, "r")
    lines = file.readlines()
    for line in reversed(lines):
        list.append(line)
    return list
    file.close()
    raise NotImplementedError()

'''
Here are some sample commands to help you run/test your implementations.
Feel free to uncomment/modify/add to them as you wish.
'''
def main():


    file_contents = read_file("sampletext.txt")
    #print(read_file_into_list("sampletext.txt"))
    write_first_line_to_file(file_contents, "online.txt")
    #print(read_even_numbered_lines("sampletext.txt"))
    #print(read_file_in_reverse("sampletext.txt"))
